/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-on-surface": "#ebf1ff",
        "primary": "#006d38",
        "on-tertiary-fixed-variant": "#653e00",
        "surface-container-lowest": "#ffffff",
        "on-error-container": "#93000a",
        "surface-tint": "#006d38",
        "error": "#ba1a1a",
        "on-primary": "#ffffff",
        "surface-container-highest": "#dce3f2",
        "surface-container-high": "#e2e8f8",
        "editor-bg": "#F9FAFB",
        "on-surface": "#151c27",
        "on-surface-variant": "#3d4a3f",
        "surface-variant": "#dce3f2",
        "on-primary-fixed-variant": "#005229",
        "surface-container": "#e7eefe",
        "on-secondary-fixed-variant": "#404758",
        "tertiary-fixed": "#ffddb8",
        "surface-dim": "#d3daea",
        "secondary-container": "#dbe2f8",
        "on-primary-fixed": "#00210d",
        "on-primary-container": "#003317",
        "on-secondary": "#ffffff",
        "on-tertiary-container": "#402500",
        "inverse-primary": "#80d999",
        "inverse-surface": "#2a313c",
        "error-container": "#ffdad6",
        "surface-bright": "#f9f9ff",
        "outline": "#6d7b6e",
        "tertiary-container": "#c28637",
        "on-secondary-container": "#5d6476",
        "on-tertiary-fixed": "#2a1700",
        "outline-muted": "#bccabc",
        "primary-fixed": "#9bf6b3",
        "tertiary-fixed-dim": "#fdb965",
        "surface": "#f9f9ff",
        "on-background": "#151c27",
        "secondary-fixed-dim": "#bfc6db",
        "background": "#f9f9ff",
        "tertiary": "#855300",
        "outline-variant": "#bccabc",
        "secondary-fixed": "#dbe2f8",
        "on-secondary-fixed": "#141b2b",
        "primary-fixed-dim": "#80d999",
        "on-error": "#ffffff",
        "secondary": "#575e70",
        "primary-container": "#4aa368",
        "surface-container-low": "#f0f3ff",
        "on-tertiary": "#ffffff",
        "search-bg": "#F4F7F5",
        "nav-active": "#E8F7EF",
        "badge-green": "#E6F4EA",
        "badge-green-text": "#137333",
        "hover-tint": "#FAFCFB"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "margin-page": "24px",
        "container-max": "1440px",
        "sidebar-width": "240px",
        "space-md": "16px",
        "gutter": "16px",
        "space-sm": "8px",
        "space-lg": "24px",
        "space-xs": "4px"
      },
      fontFamily: {
        "label-sm": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "meta-data": ["Inter", "sans-serif"]
      },
      fontSize: {
        "label-sm": ["11px", { lineHeight: "14px", fontWeight: "500" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "headline-lg": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "headline-md": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "meta-data": ["12px", { lineHeight: "16px", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}
